name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check Secrets
        run: |
          echo "Maven Username: ${{ secrets.MAVEN_USERNAME }}"
          echo "Maven Password: ${{ secrets.MAVEN_PASSWORD }}"

  deploy: 
    uses: ./.github/workflows/reusable-java-deploy.yaml
    with:
      java-version: '11'
      maven-repo-id: 'my-repo'
    secrets:
      maven-username: ${{ secrets.MAVEN_USERNAME }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}