# .github/workflows/deploy.yml
name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable-java-deploy.yaml
    with:
      java-version: '11'
      maven-repo-id: 'my-repo'
      maven-username: ${{ secrets.MAVEN_USERNAME }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}